name: 'apple_store_source'
version: '0.4.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  apple_store_source:
    app: "{{ source('apple_store', 'app_store_app') }}"
    sales_subscription_events: "{{ source('apple_store', 'sales_subscription_event_summary') }}"
    sales_subscription_summary: "{{ source('apple_store', 'sales_subscription_summary') }}"
    apple_store_country_codes: "{{ ref('apple_store_country_codes') }}"
    app_store_discovery_and_engagement_detailed_daily: "{{ source('apple_store', 'app_store_discovery_and_engagement_detailed_daily') }}"
    app_crash_daily: "{{ source('apple_store', 'app_crash_daily') }}"
    app_store_download_detailed_daily: "{{ source('apple_store', 'app_store_download_detailed_daily') }}"
    app_session_detailed_daily: "{{ source('apple_store', 'app_session_detailed_daily') }}"
    app_store_installation_and_deletion_detailed_daily: "{{ source('apple_store', 'app_store_installation_and_deletion_detailed_daily') }}"
    
    apple_store__subscription_events:
    - 'Renew'
    - 'Cancel'
    - 'Subscribe'
models:
  apple_store_source:
    materialized: table
    +schema: apple_store_source
    tmp:
      materialized: view
seeds:
  apple_store_source:
    +schema: apple_store_source
    +column_types:
      country_name: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      alternative_country_name: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      region: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      sub_region: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"