config-version: 2

name: 'apple_store_source_integration_tests'
version: '0.3.0'

profile: 'integration_tests' 

vars:
  apple_store_schema: apple_store_source_integrations_tests
  apple_store__using_subscriptions: True
  apple_store_source:
    app_identifier: "app"
    app_store_platform_version_source_type_report_identifier: "app_store_platform_version_source_type"
    app_store_source_type_device_report_identifier: "app_store_source_type_device"
    app_store_territory_source_type_report_identifier: "app_store_territory_source_type"
    crashes_app_version_device_report_identifier: "crashes_app_version"
    crashes_platform_version_device_report_identifier: "crashes_platform_version"
    downloads_platform_version_source_type_report_identifier: "downloads_platform_version_source_type"
    downloads_source_type_device_report_identifier: "downloads_source_type_device"
    downloads_territory_source_type_report_identifier: "downloads_territory_source_type"
    sales_account_identifier: "sales_account"
    sales_subscription_event_summary_identifier: "sales_subscription_events"
    sales_subscription_summary_identifier: "sales_subscription_summary"
    usage_app_version_source_type_report_identifier: "usage_app_version_source_type"
    usage_platform_version_source_type_report_identifier: "usage_platform_version_source_type"
    usage_source_type_device_report_identifier: "usage_source_type_device"
    usage_territory_source_type_report_identifier: "usage_territory_source_type"

seeds:
  apple_store_source_integration_tests:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        _fivetran_synced: timestamp
        date: timestamp
      
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']