config-version: 2

name: 'apple_store_source_integration_tests'
version: '0.5.0'

profile: 'integration_tests' 

vars:
  # apple_store__using_subscriptions: True # un-comment this line when generating docs!
  apple_store_schema: apple_store_source_integrations_tests_7
  apple_store_source:
    apple_store_app_identifier: "app_store_app"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_event_summary"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_discovery_and_engagement_standard_daily_identifier: "app_store_discovery_and_engagement_daily"
    apple_store_crash_daily_identifier: "app_crash_daily"
    apple_store_download_standard_daily_identifier: "app_store_download_daily"
    apple_store_session_standard_daily_identifier: "app_session_daily"
    apple_store_installation_and_deletion_standard_daily_identifier: "app_store_installation_and_deletion_daily"

models:
  +persist_docs:
    relation: "{{ false if target.type in ('spark','databricks') else true }}"
    columns: "{{ false if target.type in ('spark','databricks') else true }}"

seeds:
  apple_store_source_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
      date: date
      
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']